version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: crm-users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm_network

  api:
    container_name: crm_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@postgres:5432/crm-users
      NODE_ENV: development

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - postgres
    networks:
      - crm_network

networks:
  crm_network:
    name: crm_network
    driver: bridge

volumes:
  postgres_data:
    name: crm_postgres_data
